"""Add patent_analyses table

Revision ID: 0002_add_patent_analyses_table
Revises: 06966eaa7879
Create Date: 2026-02-14 05:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0002_add_patent_analyses_table'
down_revision: Union[str, Sequence[str], None] = '06966eaa7879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'patent_analyses',
        sa.Column('id', sa.String(36), primary_key=True, nullable=False),
        sa.Column('session_id', sa.String(36), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('analyzed_patents', sa.JSON(), nullable=True),
        sa.Column('patent_source', sa.String(20), nullable=True),
        sa.Column('confidence_score', sa.Float(), nullable=False, default=0.5),
        sa.Column('relevant_sections', sa.JSON(), nullable=True),
        sa.Column('analysis_metadata', sa.JSON(), nullable=True),
        sa.Column('source_type', sa.String(20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=sa.func.now()),
        mysql_engine='InnoDB',
    )

    # Create indexes
    op.create_index(op.f('ix_patent_analyses_user_id'), 'patent_analyses', ['user_id'])
    op.create_index(op.f('ix_patent_analyses_session_id'), 'patent_analyses', ['session_id'])
    op.create_index(op.f('ix_patent_analyses_patent_source'), 'patent_analyses', ['patent_source'])
    op.create_index(op.f('ix_patent_analyses_source_type'), 'patent_analyses', ['source_type'])
    op.create_index(op.f('ix_patent_analyses_confidence'), 'patent_analyses', ['confidence_score'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patent_analyses_confidence'), table_name='patent_analyses')
    op.drop_index(op.f('ix_patent_analyses_source_type'), table_name='patent_analyses')
    op.drop_index(op.f('ix_patent_analyses_patent_source'), table_name='patent_analyses')
    op.drop_index(op.f('ix_patent_analyses_session_id'), table_name='patent_analyses')
    op.drop_index(op.f('ix_patent_analyses_user_id'), table_name='patent_analyses')
    op.drop_table('patent_analyses')
    # ### end Alembic commands ###
