"""Add role column to users table

Revision ID: 06966eaa7879
Revises: 
Create Date: 2026-02-08 16:19:22.684933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06966eaa7879'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-edited to prevent dropping chatbot tables that are not in env.py imports
    # op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    # op.drop_table('conversation_sessions')
    # op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    # op.drop_index(op.f('ix_conversation_messages_timestamp'), table_name='conversation_messages')
    # op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    # op.drop_table('conversation_messages')
    # op.drop_index(op.f('ix_user_session_summaries_session_id'), table_name='user_session_summaries')
    # op.drop_index(op.f('ix_user_session_summaries_user_id'), table_name='user_session_summaries')
    # op.drop_table('user_session_summaries')
    # op.drop_index(op.f('ix_user_properties_key'), table_name='user_properties')
    # op.drop_index(op.f('ix_user_properties_user_id'), table_name='user_properties')
    # op.drop_table('user_properties')
    op.drop_index(op.f('api_key'), table_name='mcp_api_keys')
    op.drop_index(op.f('ix_mcp_api_keys_api_key'), table_name='mcp_api_keys')
    op.create_index(op.f('ix_mcp_api_keys_api_key'), 'mcp_api_keys', ['api_key'], unique=True)
    op.create_index(op.f('ix_mcp_api_keys_id'), 'mcp_api_keys', ['id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_mcp_api_keys_id'), table_name='mcp_api_keys')
    op.drop_index(op.f('ix_mcp_api_keys_api_key'), table_name='mcp_api_keys')
    op.create_index(op.f('ix_mcp_api_keys_api_key'), 'mcp_api_keys', ['api_key'], unique=False)
    op.create_index(op.f('api_key'), 'mcp_api_keys', ['api_key'], unique=True)
    
    # Hand-edited to prevent recreating chatbot tables (they were never dropped)
    # op.create_table('user_properties', ...)
    # op.create_table('user_session_summaries', ...)
    # op.create_table('conversation_messages', ...)
    # op.create_table('conversation_sessions', ...)
    # ### end Alembic commands ###
