"""Add session groups tables

Revision ID: a7b3c5d8e2f4
Revises: 06966eaa7879
Create Date: 2026-02-14 20:32:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7b3c5d8e2f4'
down_revision: Union[str, Sequence[str], None] = '06966eaa7879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create session_groups table
    op.create_table(
        'session_groups',
        sa.Column('id', sa.String(36), primary_key=True, nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('color_code', sa.String(10), nullable=False, server_default='#57373'),
        sa.Column('is_default', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('creator_user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=sa.func.now()),
        mysql_engine='InnoDB',
    )

    # Create indexes for session_groups
    op.create_index(op.f('ix_session_groups_name'), 'session_groups', ['name'])
    op.create_index(op.f('ix_session_groups_creator_user_id'), 'session_groups', ['creator_user_id'])
    op.create_index(op.f('ix_session_groups_is_default'), 'session_groups', ['is_default'])

    # Create group_members table
    op.create_table(
        'group_members',
        sa.Column('id', sa.Integer(), autoincrement=True, primary_key=True, nullable=False),
        sa.Column('group_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(50), nullable=False, server_default='member'),
        sa.Column('joined_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        mysql_engine='InnoDB',
    )

    # Create indexes for group_members
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'])
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'])
    op.create_index(op.f('ix_group_members_unique'), 'group_members', ['group_id', 'user_id'], unique=True)

    # Create session_group_tags table
    op.create_table(
        'session_group_tags',
        sa.Column('id', sa.String(36), primary_key=True, nullable=False),
        sa.Column('group_id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('color_code', sa.String(10), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        mysql_engine='InnoDB',
    )

    # Create indexes for session_group_tags
    op.create_index(op.f('ix_session_group_tags_group_id'), 'session_group_tags', ['group_id'])
    op.create_index(op.f('ix_session_group_tags_name'), 'session_group_tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes for session_group_tags
    op.drop_index(op.f('ix_session_group_tags_name'), table_name='session_group_tags')
    op.drop_index(op.f('ix_session_group_tags_group_id'), table_name='session_group_tags')
    # Drop session_group_tags table
    op.drop_table('session_group_tags')

    # Drop indexes for group_members
    op.drop_index(op.f('ix_group_members_unique'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    # Drop group_members table
    op.drop_table('group_members')

    # Drop indexes for session_groups
    op.drop_index(op.f('ix_session_groups_is_default'), table_name='session_groups')
    op.drop_index(op.f('ix_session_groups_creator_user_id'), table_name='session_groups')
    op.drop_index(op.f('ix_session_groups_name'), table_name='session_groups')
    # Drop session_groups table
    op.drop_table('session_groups')
    # ### end Alembic commands ###
